print(10 > 3)
print(10 < 3)
print(3 != 4)
print(3 != 3)
print(3 == "3")
print("mohammad" == "mohammad")
print("z" < "mohammad")
print("a" < "z")
print("ab" > "aa")
print("ا" < "ب")
print("ا" > "ب")

print(ord("c"))
print(ord("ا"))
print(ord("ب"))
print(ord("پ"))
print(ord("ت"))
print(ord("ث"))

print("ali" == "ALI")